### ISSUE TITLE
Chromium 123 added support for soundsharing on linux.

### ISSUE THREAD

**Issue by fvalasiad** [Enitoni/pulseshitter#26]
Hello!

Well, title, the shitty problem now has an actual not-shitty solution. The real issue? Getting electron to support it!

No particular request here, just curious if you guys are aware of the situation and if you could share any plans with us.

Even if electron is updated to support it btw I doubt the app developers will bother updating electron version.

**Comment by Enitoni** [comment]
If I remember correctly, Chromium has already had this support for a long time. I don't remember from where, but I don't think this is particularly new. Correct me if I am wrong.

So, the problem remains with Discord refusing to update their Electron version. Until then, software like pulseshitter, vesktop, and others, will (sadly) still have to stay relevant.

Given that this issue is not related to pulseshitter I am going to close it, as there's nothing here for me to fix or implement. You're free to continue the discussion after however.
