### ISSUE TITLE
Pulseshitter detects playback streams, but it cannot use the audio from those streams

### ISSUE THREAD

**Issue by aVastAbyss** [Enitoni/pulseshitter#28]
**Problem:** Pulseshitter launches fine and the bot joins the voice channel, but it does not stream any audio from the selected application.  The sound meter remains completely empty, even though that application is playing sound.

**OS:** Debian 12 (bookworm)
**Sound Server:** Pulseaudio 16.1

**Installed sound packages:**
- libpulse-mainloop-glib0
- libpulse0
- libpulsedsp
- pulseaudio-utils
- pulseaudio
- alsa-topology
- alsa-ucm-conf
- alsa-utils

**Installation procedure for reproducibility:**
1. Created an application in the Discord developer portal
2. Created an invite link for a bot user with the following permissions: Connect, Speak, Use Voice Activity.
3. Successfully got the bot in the desired server (a server with just me for testing purposes).
4. Downloaded the binary for the newest release of Pulseshitter.
5. Made it an executable with `sudo chmod +x pulseshitter`
6. Ran it, and then inputted the correct bot token and user ID
7. Bot successfully joined the correct VC, and Discord showed a green circle around it (demonstrating it had the proper permissions)
8. Attempted to stream a YouTube video from Firefox.
9. No audio came from the bot (I was expecting a slight echo, or for the sound meter to not be completely gray).

**Attempted solutions:**
- Streaming the audio from a different application (problem persisted for Steam games)
- Re-installing the bot
- Trying an older release version
- Using pavucontrol to see if anything was muted (no application or sound stream was muted)
- Updating all packages on my system
- Putting `--verbose` and `--show-logs` at the end of `./pulseshitter` to see if I could see any logs
- Face palming and saying "How did I not see that earlier??", in hopes of suddenly seeing the problem

**Comment by Enitoni** [comment]
Hi! Thanks for creating an issue.

Hmm, that is very strange. I'm wondering if the problem is pulseaudio. I've never actually tested pulseshitter for pulseaudio, because most distros (afaik) use pipewire now, and pipewire simply interops with the pulseaudio server API. Are you able to test the same setup with pipewire? I tested it just now in my VM running Fedora, and it works fine.

**Comment by aVastAbyss** [comment]
Thanks for the speedy response! :D
I will test it using pipewire and get back to you on that tomorrow.

**Comment by aVastAbyss** [comment]
Switching to Pipewire fixed the issue.  I guess Pulseshitter doesn't work with Pulseaudio despite the name :joy:
or at least not for me...

Thanks!

**Comment by Enitoni** [comment]
Yeah, that's very strange. Admittedly I picked the name because "pulseaudio" is generally what people think of when they think audio on Linux. I'd be open to figuring out why it doesn't work directly with pulseaudio (despite using the pulseaudio api bindings and everything) when I have time. Thank you for bringing it to my attention!
